title         : 'David Valles - Personal Trainer'
email         : davidtjvalles@gmail.com
author        : 'David Valles'
description   : 'David Valles - Personal Trainer'

baseurl       : ''
url           : 'http://dtjv.io'

date_format   : '%b %-d, %Y'
permalink     : /:year/:month/:title/

paginate      : 5
paginate_path : '/blog/page-:num/'

include:
  - '_pages'

exclude:
  - 'vendor'
  - '_assets'
  - 'gulpfile.js'
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'NOTES.md'
  - 'node_modules'
  - 'package.json'
  - 'package-lock.json'

plugins:
  - 'jekyll-paginate'
  - 'jekyll-sitemap'

config:
  assets:
    imgs:
      src: '_assets/imgs/**/*'
      dest: 'assets/imgs'
    styles:
      src: '_assets/styles/main.scss'
      dest:
        production: '_includes/css'
        development: 'assets/styles'
  vendor:
    styles:
      src: 'node_modules/materialize-css/sass/**/*'
      dest: '_assets/styles/materialize'
    fonts:
      src: 'node_modules/materialize-css/dist/fonts/**/*'
      dest: 'assets/fonts'
    js:
      src: 'node_modules/materialize-css/dist/js/materialize.min.js'
      dest: 'assets/js'

