title                : 'David Valles'
email                : davidtjvalles@gmail.com
author               : 'David Valles'
description          : 'David Valles'

baseurl              : ''
url                  : 'http://davidvalles.net'

date_format          : '%b %-d, %Y'
permalink            : /:year/:month/:title/

paginate             : 5
paginate_path        : '/blog/page-:num/'

markdown             : kramdown
highligher           : rouge
kramdown             :
  input              : GFM
  hard_wrap          : false

# Sections
animated             : true
show_related_posts   : false
show_social_icons    : true
enable_mathjax       : true
enable_anchorjs      : true
ajaxify_contact_form : true

# Google
google_analytics     :

# Bing
bing_verification    :

# Disqus
disqus_shortname     : davidvalles

# Social Icons
github_username      : dtjv
bitbucket_username   :
stackoverflow_id     :
xmlfeed              :
twitter_username     :
facebook_username    :
skype_username       :
steam_nickname       :
google_plus_id       :
linkedin_username    :
angellist_username   :
medium_id            :
bitcoin_url          :
paypal_url           :
flattr_button        :

# Share Icons
show_sharing_icons   : false
share_facebook       : false
share_twitter        : false

# UI
text                 :
  pagination         :
    newer            : 'Next'
    older            : 'Previous'
  post               :
    updated          : 'Updated'
    minute_read      : 'minute read'
    related_posts    : 'Related Posts'
  index              :
    coming_soon      : 'Coming soon!!'

include:
  - '_pages'

exclude:
  - 'vendor'
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'NOTES.md'
  - 'node_modules'
  - 'package.json'
  - 'package-lock.json'

plugins:
  - 'jekyll-paginate'
  - 'jekyll-sitemap'
