# 1. mkdir _config
# 1. touch _config/index.js
# 1. touch _config/config.js
#
# index.js will require config.js, write the site config to _config.yml using
# js-yaml.
#
# config.js will also hold build paths. gulpfile.js will read in config.js paths
title         : 'David Valles - Personal Trainer'
email         : davidtjvalles@gmail.com
author        : 'David Valles'
description   : 'David Valles - Personal Trainer'

baseurl       : ''
url           : 'http://dtjv.io'

date_format   : '%b %-d, %Y'
permalink     : /:year/:month/:title/

paginate      : 5
paginate_path : '/blog/page-:num/'

include       : ['_pages']
exclude       : ['vendor',
                 '_assets',
                 'Gemfile',
                 'Gemfile.lock',
                 'node_modules',
                 'package.json',
                 'package-lock.json',
                 'gulpfile.js',
                 'README.md',
                 'LICENSE.md']

plugins       : ['jekyll-paginate',
                 'jekyll-sitemap']
